/**
 * This file is autogenerated by helper.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/helper/contract";

const deployedContracts = {
  11155111: {
    EncryptedHireForm: {
      address: "0x3b9e7100AB97F227F3F96A529F4c9D3F0DaEA8bc",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "candidate",
              type: "address",
            },
          ],
          name: "hasResponse",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "protocolId",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "externalEuint32",
              name: "encryptedData",
              type: "bytes32",
            },
            {
              internalType: "bytes",
              name: "zkProof",
              type: "bytes",
            },
          ],
          name: "uploadResponse",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "candidate",
              type: "address",
            },
          ],
          name: "viewEncryptedResponse",
          outputs: [
            {
              internalType: "euint32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 9368216,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
