/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EncryptedHireFormInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "hasResponse"
      | "protocolId"
      | "uploadResponse"
      | "viewEncryptedResponse"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "hasResponse",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "uploadResponse",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "viewEncryptedResponse",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "hasResponse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "uploadResponse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "viewEncryptedResponse",
    data: BytesLike
  ): Result;
}

export interface EncryptedHireForm extends BaseContract {
  connect(runner?: ContractRunner | null): EncryptedHireForm;
  waitForDeployment(): Promise<this>;

  interface: EncryptedHireFormInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  hasResponse: TypedContractMethod<[candidate: AddressLike], [boolean], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  uploadResponse: TypedContractMethod<
    [encryptedData: BytesLike, zkProof: BytesLike],
    [void],
    "nonpayable"
  >;

  viewEncryptedResponse: TypedContractMethod<
    [candidate: AddressLike],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "hasResponse"
  ): TypedContractMethod<[candidate: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "uploadResponse"
  ): TypedContractMethod<
    [encryptedData: BytesLike, zkProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "viewEncryptedResponse"
  ): TypedContractMethod<[candidate: AddressLike], [string], "view">;

  filters: {};
}
